export const infoArray = [
    {
        currency: "AUD/USD",
        timeInterval: "23h",
        payout: "Payout",
        payoutMoney: "$2.00",
        market: "Market",
        marketMoney: "112.368",
        isOpen: true,
        isUp: true,
    },
    {
        currency: "AUD/USD",
        timeInterval: "15m",
        payout: "Payout",
        payoutMoney: "$3.00",
        market: "Market",
        marketMoney: "112.368",
        isOpen: true,
        isUp: true,
    },
    {
        currency: "AUD/USD",
        timeInterval: "1h",
        payout: "Payout",
        payoutMoney: "$9.00",
        market: "Market",
        marketMoney: "112.368",
        isOpen: true,
        isUp: false,
    },
    {
        currency: "AUD/USD",
        timeInterval: "3h",
        payout: "Payout",
        payoutMoney: "$8.00",
        market: "Market",
        marketMoney: "112.368",
        isOpen: true,
        isUp: true,
    },
    {
        currency: "BBD/USD",
        timeInterval: "3h",
        payout: "Payout",
        payoutMoney: "$90.00",
        market: "Market",
        marketMoney: "192.888",
        isOpen: false,
        isUp: false,
    },
    {
        currency: "AUD/USD",
        timeInterval: "23h",
        payout: "Payout",
        payoutMoney: "$2.00",
        market: "Market",
        marketMoney: "112.368",
        isOpen: true,
        isUp: false,
    },
    {
        currency: "AUD/USD",
        timeInterval: "15m",
        payout: "Payout",
        payoutMoney: "$3.00",
        market: "Market",
        marketMoney: "112.368",
        isOpen: true,
        isUp: true,
    },
    {
        currency: "AUD/USD",
        timeInterval: "1h",
        payout: "Payout",
        payoutMoney: "$9.00",
        market: "Market",
        marketMoney: "112.368",
        isOpen: true,
        isUp: false,
    },
    {
        currency: "AUD/USD",
        timeInterval: "3h",
        payout: "Payout",
        payoutMoney: "$8.00",
        market: "Market",
        marketMoney: "112.368",
        isOpen: true,
        isUp: true,
    },
    {
        currency: "BBD/USD",
        timeInterval: "3h",
        payout: "Payout",
        payoutMoney: "$90.00",
        market: "Market",
        marketMoney: "192.888",
        isOpen: false,
        isUp: false,
    },
    {
        currency: "AUD/USD",
        timeInterval: "23h",
        payout: "Payout",
        payoutMoney: "$2.00",
        market: "Market",
        marketMoney: "112.368",
        isOpen: true,
        isUp: false,
    },
    {
        currency: "AUD/USD",
        timeInterval: "15m",
        payout: "Payout",
        payoutMoney: "$3.00",
        market: "Market",
        marketMoney: "112.368",
        isOpen: true,
        isUp: true,
    },
    {
        currency: "AUD/USD",
        timeInterval: "1h",
        payout: "Payout",
        payoutMoney: "$9.00",
        market: "Market",
        marketMoney: "112.368",
        isOpen: true,
        isUp: true,
    },
    {
        currency: "AUD/USD",
        timeInterval: "3h",
        payout: "Payout",
        payoutMoney: "$8.00",
        market: "Market",
        marketMoney: "112.368",
        isOpen: true,
        isUp: false,
    },
    {
        currency: "BBD/USD",
        timeInterval: "3h",
        payout: "Payout",
        payoutMoney: "$90.00",
        market: "Market",
        marketMoney: "192.888",
        isOpen: false,
        isUp: true,
    },
]