export const activityData = [
    {
        asset: "USD/JPY",
        strike: 118.629,
        startTime: "20:47",
        expiry: "21:00",
        status: "Opened",
        closingRate: "-",
        investment: "$500",
        payOut: "$600",
        isUp: true,
        takePayout: "SELL",
    },
    {
        asset: "USD/JPY",
        strike: 118.629,
        startTime: "20:47",
        expiry: "21:00",
        status: "Opened",
        closingRate: "-",
        investment: "$500",
        payOut: "$600",
        isUp: true,
        takePayout: "CANCEL",
    },
    {
        asset: "USD/JPY",
        strike: 118.629,
        startTime: "20:47",
        expiry: "21:00",
        status: "Opened",
        closingRate: "-",
        investment: "$500",
        payOut: "$600",
        isUp: false,
        takePayout: "SELL",
    },
    {
        asset: "USD/JPY",
        strike: 118.629,
        startTime: "20:47",
        expiry: "21:00",
        status: "Opened",
        closingRate: "-",
        investment: "$500",
        payOut: "$600",
        isUp: true,
        takePayout: "SELL",
    },
    {
        asset: "USD/JPY",
        strike: 118.629,
        startTime: "20:47",
        expiry: "21:00",
        status: "Opened",
        closingRate: "-",
        investment: "$500",
        payOut: "$600",
        isUp: false,
        takePayout: "SELL",
    },
    {
        asset: "USD/JPY",
        strike: 118.629,
        startTime: "20:47",
        expiry: "21:00",
        status: "Opened",
        closingRate: "-",
        investment: "$500",
        payOut: "$600",
        isUp: true,
        takePayout: "SELL",
    },
    {
        asset: "USD/JPY",
        strike: 118.629,
        startTime: "20:47",
        expiry: "21:00",
        status: "Opened",
        closingRate: "-",
        investment: "$500",
        payOut: "$600",
        isUp: false,
        takePayout: "SELL",
    },
    {
        asset: "USD/JPY",
        strike: 118.629,
        startTime: "20:47",
        expiry: "21:00",
        status: "Opened",
        closingRate: "-",
        investment: "$500",
        payOut: "$600",
        isUp: false,
        takePayout: "SELL",
    },
    {
        asset: "USD/JPY",
        strike: 118.629,
        startTime: "20:47",
        expiry: "21:00",
        status: "Opened",
        closingRate: "-",
        investment: "$500",
        payOut: "$600",
        isUp: true,
        takePayout: "SELL",
    }
]